### ISSUE TITLE
BUG改进

### ISSUE THREAD

**Issue by sky22333** [jat001/docker-sspanel-uim#2]
`docker-compose.core.yaml`文件里52行的`/app/docker-cron.sh`没有映射，会导致部署报错。

请在57行添加一个映射：`- ./docker-cron.sh:/app/docker-cron.sh`

**Comment by eunrui** [comment]
请问在`.config.php`中没有提到的db_driver你填的是什么呀?`docker-tool.php`需要这个变量
```
[2024-05-06 23:40:38] Creating database...
[06-May-2024 15:40:38 UTC] PHP Warning:  Undefined array key "db_driver" in /app/docker-tool.php on line 54
[06-May-2024 15:40:38 UTC] PHP Fatal error:  Uncaught TypeError: Cannot assign null to property Tool::$db_driver of type string in /app/docker-tool.php:54
Stack trace:
#0 /app/docker-tool.php(206): Tool->__construct()
#1 {main}
  thrown in /app/docker-tool.php on line 54
```

**Comment by sky22333** [comment]
> 想知道在`.config.php`没有提到的 db_driver 中你填写的是什么呀？`docker-tool.php`需要这个变量
> 
> ```
> [2024-05-06 23:40:38] Creating database...
> [06-May-2024 15:40:38 UTC] PHP Warning:  Undefined array key "db_driver" in /app/docker-tool.php on line 54
> [06-May-2024 15:40:38 UTC] PHP Fatal error:  Uncaught TypeError: Cannot assign null to property Tool::$db_driver of type string in /app/docker-tool.php:54
> Stack trace:
> #0 /app/docker-tool.php(206): Tool->__construct()
> #1 {main}
>   thrown in /app/docker-tool.php on line 54
> ```

提供你的TG，我帮你看看

**Comment by eunrui** [comment]
> > 想知道在`.config.php`没有提到的 db_driver 中你填写的是什么呀？`docker-tool.php`需要这个变量
> > ```
> > [2024-05-06 23:40:38] Creating database...
> > [06-May-2024 15:40:38 UTC] PHP Warning:  Undefined array key "db_driver" in /app/docker-tool.php on line 54
> > [06-May-2024 15:40:38 UTC] PHP Fatal error:  Uncaught TypeError: Cannot assign null to property Tool::$db_driver of type string in /app/docker-tool.php:54
> > Stack trace:
> > #0 /app/docker-tool.php(206): Tool->__construct()
> > #1 {main}
> >   thrown in /app/docker-tool.php on line 54
> > ```
> 
> 提供你的TG，我帮你看看

https://t.me/eunrui, 感谢, 我看`docker-tool.php`里面要从`.env`里取配置的参数还有很多呀
